syntax on
set nocompatible
 
set nu
set ru
set ai
set smartindent
set t_Co=256
set history=100
set ruler
set hlsearch
 
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab     "Converting tabs to spaces
 
set cursorline
 
colorscheme zenburn
set gfn=Monaco:h14